### ISSUE TITLE
Error: render error in "airflow/templates/deployments-web.yaml": at <.Values.temp.path>: nil pointer evaluating interface {}.path

### ISSUE THREAD

**Issue by octopyth** [godatadriven/airflow-helm#3]
First of all: great work on the blog post:
https://blog.godatadriven.com/airflow-on-aks

I follow the blog post instructions until the crescendo:
```
helm install --namespace "airflow" --name "airflow" -f airflow-local.yaml airflow/
```

Then I get the following error:
```
Error: render error in "airflow/templates/deployments-web.yaml": template: airflow/templates/deployments-web.yaml:87:35: executing "airflow/templates/deployments-web.yaml" at <.Values.temp.path>: nil pointer evaluating interface {}.path
```

I figured out that the temp path has not been explicitly included in the blog post, even though it is included in airflow-local.yaml. 
```
  temp:
    secretName: azure-file-airflow-temp
    shareName: airflow-temp
```

I have created a file share in Azure with name airflow-temp, but it didn't fix the error.

I must be missing something.
Thanks!

**Comment by octopyth** [comment]
I figured it out. In airflow-local.yaml, right after
```
logs:
  path: /usr/local/airflow/logs

dags:
  path: /usr/local/airflow/dags
  doNotPickle: false
```
I added
```
temp:
  path: usr/local/airflow/temp
```
I am closing the issue and will open a pull request.
Thanks for sharing!

**Comment by Pverheijen** [comment]
It worked for me but with a slash in front of usr

so 

`
    path: /usr/local/airflow/temp
`

**Comment by Pverheijen** [comment]
I've had to downgrade to helm v2 with, else flag --name wasn't allowed.

`choco install kubernetes-helm --version=2.14.0`

After this I've gotten an error: 

Error: release airflow failed: namespaces "airflow-on-aks" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "airflow"

Running this solved the problem:

```
kubectl --namespace kube-system create serviceaccount tiller

kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller

helm init --service-account tiller --upgrade
```
